### PR TITLE
Design update for partner page

### PR DESCRIPTION
**Pull request by luk-str**
This is a draft of a design update to the partner page. Currently under construction 🏗️ 

Will close issue #181 when done 👌

### CODE REVIEW

**Comment by luk-str** [comment]
I think it's ready for review 👍 

I'm a bit unsure about the design as the new figma files don't include supporters/allied partners and the screenshot in the issue is probably outdated. Open for changes 🥸

**Comment by luk-str** [comment]
Oh and this probably also closes issue #219 🔨

**Review by hexjelly — COMMENTED** [review]
Looks good. And yea it's a bit unfortunate with all the changes in the design and not always keeping these issues updated as things happen, and it ends up a bit forgotten 🙈

I have one idea for a change, if it's not too much of a hassle and you also agree with it :D

Instead of doing the `&:after ... etc` for dividers, maybe we should just simply use a styled `<hr />` between the containers? It might be better semantically, and also accessibility-wise (I believe it should have the proper role attribute and all that jazz). What do you think?

**Comment by luk-str** [comment]
@hexjelly I agree, `<hr /> `will be a better choice for sure!

I'll try to take care of it soon 🙌

**Pull request closed without merging**
