### PR TITLE
Remove subheading line

### PR DESCRIPTION
**Pull request by luk-str**
- [x] Remove line from the sub-heading component
- [x] Remove all line-defining props passed to the sub-heading component in other components and pages

Fixes issue #180 ✌🏻

### CODE REVIEW

**Comment by luk-str** [comment]
Basically ready for review, although the github check fails for some reason.
The Lint command fails with exit code 127. Any ideas? 🤔

**Comment by hexjelly** [comment]
Sorry I never got any notification about these PRs, I'll have a look at it as soon as I can before the end of the week. As well as fixing the github action problem!

**Comment by luk-str** [comment]
Sure, no problem! Awesome, thanks!
I'll make sure to add a tag next time 😊

**Comment by hexjelly** [comment]
Sorry for the spam on these PRs. I fixed the issue with the Github action, then there was a weird issue with Netlify previews and the status checks for those that wasn't immediately obvious. Once that was fixed it decided to do builds for every push of previously submitted commits 🙄

**Comment by luk-str** [comment]
Yeah I noticed, haha, no worries. Cool that it's fixed now 🤘🏻

**Review by hexjelly — APPROVED** [review]

**Comment by hexjelly** [comment]
Thank you so much for the contribution! I don't see any obvious issues 🎉

**Pull request merged**
